import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import AppSidebar from "@/components/common/AppSidebar";
import Navbar from "@/components/common/Navbar";
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";
import NotificationProvider from "@/context/notification-context";
import { ThemeProvider } from "@/components/common/theme-provider";
import { cookies } from "next/headers";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable} bg-background font-sans antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NotificationProvider>
            <SidebarProvider defaultOpen={defaultOpen}>
              {/* <div className="flex min-h-screen overflow-hidden gap-10"> */}
              {/* Sidebar */}
              <AppSidebar />

              {/* Main Content */}
              <SidebarInset className="ml-5 px-5">
                <Navbar />
                <div className="">{children}</div>
              </SidebarInset>
              {/* </div> */}
            </SidebarProvider>
          </NotificationProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
